# Generated by Django 6.1.1 on 2026-09-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('project', 'Project'), ('experience', 'Experience'), ('skill', 'Skill'), ('blog', 'Blog post'), ('certification', 'Certification')], max_length=20)),
                ('source_id', models.CharField(help_text='Matches the id used in the frontend content JSON.', max_length=100)),
                ('text', models.TextField(help_text='The actual grounded content, in plain prose.')),
                ('source_url', models.URLField(blank=True, help_text='Public URL this chunk should link back to.')),
            ],
        ),
    ]
